# Generated by Django 5.2.5 on 2025-08-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='character',
            field=models.CharField(default='anonym', max_length=100),
        ),
    ]
