# Generated by Django 5.2.5 on 2025-08-31 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_character_alter_track_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracks.character'),
        ),
    ]
