# Generated by Django 5.2.5 on 2025-09-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_alter_track_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='release_date',
        ),
        migrations.AddField(
            model_name='track',
            name='release_year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
