# Generated by Django 5.2.5 on 2025-08-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_image',
            new_name='image',
        ),
    ]
